# Generated by Django 4.1.7 on 2023-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='isbn',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
