# Generated by Django 4.1.7 on 2023-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_alter_buku_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='buku',
            name='cover_url',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
