# Generated by Django 4.1.7 on 2023-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0003_buku_cover_buku_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.TextField(blank=True, null=True),
        ),
    ]
