# Generated by Django 4.1.7 on 2023-03-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_alter_buku_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='files/cover/'),
        ),
    ]
