# Generated by Django 4.1.7 on 2023-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0006_alter_buku_authors_alter_buku_kategoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jenis_pustaka',
            field=models.IntegerField(choices=[(1, 'Fiksi'), (2, 'Non Fiksi')], null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='kategori_buku',
            field=models.IntegerField(choices=[(1, 'Lepas'), (2, 'Berjilid')], null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='kategori_jenis',
            field=models.IntegerField(choices=[(1, 'Terjemahan'), (2, 'Non Terjemahan')], null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='kelompok_pembaca',
            field=models.IntegerField(choices=[(1, 'Anak'), (2, 'Dewasa'), (3, 'Semua Umur')], null=True),
        ),
    ]
