# Generated by Django 4.1.7 on 2023-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0007_buku_jenis_pustaka_buku_kategori_buku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='file_buku',
            field=models.FileField(blank=True, null=True, upload_to='files/isibuku/'),
        ),
    ]
